### PR TITLE
Update getFirmwareUrl/getFirmwareUrls for beta

### PR DESCRIPTION
**Pull request by Cryptiiiic**

### CODE REVIEW

**Comment by DanTheMann15** [comment]
this needs fixing,

"FIRMWARE_BETA_JSON_PATH" is defined twice on lines 97 and 98, this is easily fixed by deleting line 97.

but compilation fails because:
`main.c:417:27: error: too few arguments to function 'getListOfiOSForDevice'`

problem code:
`char **versions = getListOfiOSForDevice(firmwareTokens, devVals.deviceModel, versVals.isOta, &versionCnt);`

tsschecker.h:93:8: note: declared here
`char **getListOfiOSForDevice(jssytok_t *tokens, const char *device, int isOTA, int *versionCntt, bool beta);`

this is built via automake/autogen on MSYS2.
[buildlog_msys2_mingw64.txt](https://github.com/1Conan/tsschecker/files/9843372/buildlog_msys2_mingw64.txt)

adding a zero as an argument to the code there allows me to build tsschecker, but that function may not work as intended.

//
also side note, if it comes to using `--beta` to check beta ipsw signing status, i would advise editing this line:
main.c:91: `printf("      --beta\t\t\trequest tickets for a beta instead of normal release (use with -o)\n");`
To:
main.c:91: `printf("      --beta\t\t\trequest tickets for a beta instead of a normal release\n");`

of course you can alter this to whatever makes more sense.

**Comment by Cryptiiiic** [comment]
beta doesn't use .ipsw url api for betas yet so -o is still required

**Comment by Cryptiiiic** [comment]
@DanTheMann15 how's these 3

**Comment by DanTheMann15** [comment]
👍

**Pull request merged**
